// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("MonadFeature")>]
[<assembly: AssemblyProductAttribute("MonadFeature")>]
[<assembly: AssemblyDescriptionAttribute("The project is aimed at studying F and functional programming.")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "MonadFeature"
    let [<Literal>] AssemblyProduct = "MonadFeature"
    let [<Literal>] AssemblyDescription = "The project is aimed at studying F and functional programming."
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
